server:
  port: 8080
  error:
    include-stacktrace: never

aws:
  region: "us-west-2"

token:
  age:
    refresh: 2592000
    access: 10800
    authToken: 600
    deviceCode: 600
    authCookie: 2592000

spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://cognito-idp.us-west-2.amazonaws.com/us-west-2_DWQyxBTOf"

oauth:
  client-id: "3ad886knkeo0vuvvpnvtp6rtlq"
  client-secret: "r5qd4fhj931vvlbf2oi3dhe58kjtfk2n7i70da7kc2d08sccch5"

---
spring:
  profiles: local

server:
  port: ${APP_PORT:8087}

dynamodb:
  accounts: "archipelago-local.accounts"
  account-mapping: "archipelago-local.accounts-mapping"
  accounts-git: "archipelago-local.accounts-git"
  access-keys: "archipelago-local.access-keys"
  auth-codes: "archipelago-local.auth-codes"
  auth-users: "archipelago-local.auth-users"
  auth-clients: "archipelago-local.auth-clients"
  auth-jwks: "archipelago-local.auth-jwks"

url:
  auth-server: ${APP_URL:http://localhost:8087}
  frontend: ${FRONTEND_URL:http://localhost:3000}

aws:
  access:
    id: "AKIARDAF5R4OODU52YJR"
    key: "HRG7W4XQESB1ixNknOhZ4dYRgnvAk/U3NgUOF7fH"

---
spring:
  profiles: alpha

dynamodb:
  accounts: "archipelago-alpha.accounts"
  account-mapping: "archipelago-alpha.accounts-mapping"
  accounts-git: "archipelago-alpha.accounts-git"
  access-keys: "archipelago-alpha.access-keys"
  auth-codes: "archipelago-alpha.auth-codes"
  auth-users: "archipelago-alpha.auth-users"
  auth-clients: "archipelago-alpha.auth-clients"
  auth-jwks: "archipelago-alpha.auth-jwks"

url:
  auth-server: "http://auth.alpha.archipelago.build"
  frontend: "http://alpha.archipelago.build"

aws:
  access:
    id: "AKIARDAF5R4OPZCANF5C"
    key: "GeQkTltLRCqJAEiQaK4xn0S/W2bz3+vw3KWvIyK2"

---
spring:
  profiles: beta
---
spring:
  profiles: prod

auth:
  url: ${APP_URL:http://auth.archipelago.build}
